### ISSUE TITLE
Running inference code

### ISSUE THREAD

**Issue by Gitlyz007** [moriyaya/CollaBA#2]
When I tried to run the inference code, there was something went wrong.

The inference code depends on:
`from basicsr.archs.rrdbnet_arch import RRDBNet
from basicsr.archs.mirnetv2_arch import MIRNetv2
from basicsr.archs.mirnetv2atten_arch import MIRNetv2atten
from basicsr.archs.mirnetv2ueatten_arch import MIRNetv2ueatten`

But these files seem to missing.

P.S. In fact, I was hoping to do some qualitative comparisons on RELLISUR (x2 and x4), and would appreciate it if you'd like to share the result files directly.

**Comment by moriyaya** [comment]
Sorry for the inconvenience. We have provided the results of our qualitative comparisons. You can download the results of our method from Baidu Cloud using the following link:
https://pan.baidu.com/s/1WGpKBIQ7O8SD8xK90iDbVQ
Access Code: nlvs

**Comment by Gitlyz007** [comment]
Many thanks :)

**Comment by XuRan-Zhao** [comment]
> Sorry for the inconvenience. We have provided the results of our qualitative comparisons. You can download the results of our method from Baidu Cloud using the following link: https://pan.baidu.com/s/1WGpKBIQ7O8SD8xK90iDbVQ Access Code: nlvs

Hello, this link is no longer working. Could you please provide it again?

**Comment by moriyaya** [comment]
We apologize for the inconvenience. The file shared via Baidu Netdisk:
Link: https://pan.baidu.com/s/1oAPbZOo-3RzS2ybJoohBqA?pwd=tmc5
Extraction Code: tmc5


________________________________
发件人: xuran Zhao ***@***.***>
发送时间: 2026年2月26日 15:19
收件人: moriyaya/CollaBA ***@***.***>
抄送: moriyaya ***@***.***>; Comment ***@***.***>
主题: Re: [moriyaya/CollaBA] Running inference code (Issue #2)

[https://avatars.githubusercontent.com/u/82452037?s=20&v=4]XuRan-Zhao left a comment (moriyaya/CollaBA#2)<https://github.com/moriyaya/CollaBA/issues/2#issuecomment-3964607494>

Sorry for the inconvenience. We have provided the results of our qualitative comparisons. You can download the results of our method from Baidu Cloud using the following link: https://pan.baidu.com/s/1WGpKBIQ7O8SD8xK90iDbVQ Access Code: nlvs

Hello, this link is no longer working. Could you please provide it again?

―

**Comment by XuRan-Zhao** [comment]
> We apologize for the inconvenience. The file shared via Baidu Netdisk:
> Link: https://pan.baidu.com/s/1oAPbZOo-3RzS2ybJoohBqA?pwd=tmc5
> Extraction Code: tmc5
> […](#)

Thanks
